spring.application.name=parser-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/parser_db
spring.datasource.username=swapnilbagate
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=parser-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.swap.parserservice.dto.SmsEventDto
spring.kafka.consumer.properties.spring.json.trusted.packages=com.swap.parserservice.dto
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

gemini.api.key=
gemini.model=gemini-2.5-flash